nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: https://github.com/chenxia31

projects_url: https://github.com/chenxia31

colorscheme: classic

customize:
    gravatar: 
        email: xuchenlong796@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: https://gravatar.com/xuchenlong796
        gravatar: true
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: https://gravatar.com/xuchenlong796
        gravatar: true
      android:
        url: https://gravatar.com/xuchenlong796
        gravator: true
      apple:
        url: https://gravatar.com/xuchenlong796
        gravator: true
    social_links:
        github: https://github.com/tzvetkov75/solar-theme-hexo
        twitter: /
        facebook: /
        linkedin: /
    post_count: 10
    highlight: lightcode

# keept it like this to add the root path (probably a bug)
root: ..

solar:
    # factor between 0 (fast), 1(normal), 2(very slow)  
    speed: 1
    sun_image: /images/sun.png
    earth_image: /images/earth.png
    jupiter_image: /images/jupiter.png
    mars_image: /images/mars.png
    mercury_image: /images/mercury.png
    shadow_image: /images/shadow.png
    venus_image: /images/venus.png

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: chenxiablog
    google_analytics: 'G-KW8E40YS1V'

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
